[package]
name = "examples"
version = "0.1.0"
authors = ["Koki Kato <koki.kato1994@gmail.com>"]
edition = "2018"

[[bin]]
name = "kvs_server"
path = "src/kvs/server.rs"

[dependencies]
repc = { path = "../repc" }
