[package]
name = "repc-build"
version = "0.1.0"
authors = ["Koki Kato <koki.kato1994@gmail.com>"]
edition = "2018"

[dependencies]
prost-build = "0.6"
tonic-build = "0.3"
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"